version: "2.1" 
services:
  postgresql:
    image: "postgres:14-alpine"
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres" ]
      timeout: 45s
      interval: 1s
      retries: 10
  pg-migrate:
    image: "migrate/migrate"
    network_mode: "host"
    volumes:
      - .:/src
    command: "-database postgres://postgres:mysecretpassword@localhost:5432/postgres?sslmode=disable -path /src/service.menu/queries/internal/migrations up"
    depends_on:
      postgresql:
        condition: service_healthy
  eventstore:
    image: "eventstore/eventstore:21.10.2-buster-slim"
    ports: 
      - "2113:2113"
      - "1113:1113"
    command: "--insecure --run-projections=All --enable-atom-pub-over-http"