version: "3" 
services:
  postgresql:
    image: "postgres:15-alpine"
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: mysecretpassword
  eventstore:
    image: "eventstore/eventstore:22.10.0-buster-slim"
    ports: 
      - "2113:2113"
      - "1113:1113"
    command: "--insecure --run-projections=All --enable-atom-pub-over-http"
  init-script:
    build: .
    network_mode: "host"
    volumes:
    - ../:/src
    restart: on-failure:10
